import type { Metadata } from "next";
import { Bai_Jamjuree } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/lib/providers/query-provider";
import { Toaster } from "@/lib/providers/toaster-provider";
import { StoreProvider } from "@/lib/providers/store-provider";
import { SessionInitializer } from "@/components/auth/session-initializer";

const bai_Jamjuree = Bai_Jamjuree({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body className={`${bai_Jamjuree.className} antialiased`}>
        <StoreProvider>
          <SessionInitializer />
          <QueryProvider>
            <main>{children}</main>
          </QueryProvider>
        </StoreProvider>
        <Toaster />
      </body>
    </html>
  );
}
